/*
 * Copyright (c) 2022.
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 3.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://www.gnu.org/licenses/gpl-3.0.en.html.
 */

package com.isaakhanimann.journal.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2F5DA8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A40)
val md_theme_light_secondary = Color(0xFF6841D0)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF20005E)
val md_theme_light_tertiary = Color(0xFFA11FA5)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD6F7)
val md_theme_light_onTertiaryContainer = Color(0xFF37003A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF140463)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF140463)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF3EEFF)
val md_theme_light_inverseSurface = Color(0xFF2A2277)
val md_theme_light_inversePrimary = Color(0xFFACC7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF2F5DA8)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFACC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F68)
val md_theme_dark_primaryContainer = Color(0xFF0A458F)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_secondary = Color(0xFFCEBDFF)
val md_theme_dark_onSecondary = Color(0xFF380095)
val md_theme_dark_secondaryContainer = Color(0xFF5021B8)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DDFF)
val md_theme_dark_tertiary = Color(0xFFFFAAF7)
val md_theme_dark_onTertiary = Color(0xFF5A005E)
val md_theme_dark_tertiaryContainer = Color(0xFF800084)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6F7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF140463)
val md_theme_dark_onBackground = Color(0xFFE3DFFF)
val md_theme_dark_surface = Color(0xFF140463)
val md_theme_dark_onSurface = Color(0xFFE3DFFF)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF140463)
val md_theme_dark_inverseSurface = Color(0xFFE3DFFF)
val md_theme_dark_inversePrimary = Color(0xFF2F5DA8)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFACC7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2F5DA8)